[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "https://wadjet.seg.br/*"
  to = "https://gerenciador.wadjet.seg.br/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://wadjet.seg.br/*"
  to = "https://gerenciador.wadjet.seg.br/:splat"
  status = 301
  force = true